sudo: required
services:
  - docker

before_install:
  - docker build -t aeghobor/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aeghobor/react-test npm test -- --coverage

after_success:
  - docker build -t aeghobor/multidocker-client ./client
  - docker build -t aeghobor/multidocker-nginx ./nginx
  - docker build -t aeghobor/multidocker-server ./server
  - docker build -t aeghobor/multidocker-worker ./worker

  #push the images to dockerhub
  #but before then we need to login docker cli with the account which automatically links with dockerhub
  #set these variables in travis-ci and then run the command below to login.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aeghobor/multidocker-client
  - docker push aeghobor/multidocker-nginx
  - docker push aeghobor/multidocker-server
  - docker push aeghobor/multidocker-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-336209744632"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
